name: hive_crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs), backed by a Hive store.
version: 1.0.3
homepage: https://github.com/cachapa/hive_crdt
repository: https://github.com/cachapa/hive_crdt
issue_tracker: https://github.com/cachapa/hive_crdt/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crdt: ^4.0.1
  hive: ^2.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.8
