name: hive_crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs), backed by a Hive store.
version: 0.1.0
homepage: https://github.com/cachapa/hive_crdt
repository: https://github.com/cachapa/hive_crdt
issue_tracker: https://github.com/cachapa/hive_crdt/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  crdt: ^3.0.0
  hive: ^1.4.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.4