name: crdt_hive
description: A CRDT backed by a Hive store.
version: 1.0.0
homepage: https://github.com/cachapa/crdt_hive

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  crdt: ^2.2.2
  hive: ^1.4.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.7
