name: crdt_hive
description: A CRDT backed by a Hive store.
version: 1.0.0-pre.4
homepage: https://pub.dev/packages/crdt_hive
repository: https://github.com/cachapa/crdt_hive
issue_tracker: https://github.com/cachapa/crdt_hive/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  crdt: ^3.0.0-pre
  hive: ^1.4.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.4