name: Quality Gate

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Verify code formatting
        run: dart format --set-exit-if-changed .
      - name: Get dependencies
        run: pub get
      - name: Static code analysis
        run: dart analyze --fatal-infos
      - name: Run tests
        run: dart test
